name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Node version
      run: node --version
    - name: npm version 
      run: npm --version
    - name: Install dependencies 
      run: npm ci
    - name: Run build script inside package.json
      run: npm run build --if-present

    - name: Start Node.js server
      run: node app.js &
      background: true

    - name: Delay for server startup
      run: sleep 10s

    - name: Check server status
      run: curl -Is http://localhost:puerto | head -n 1 | grep 200
      continue-on-error: true

    - name: Detener el servidor
      if: ${{ success() }}
      run: kill $(lsof -t -i:${{puerto}})

    - name: Otro paso del flujo de trabajo
      if: ${{ success() }}
      run: echo "Continuar con el siguiente paso"
        
      
    - run: npm test
