name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Node version
      run: node --version
    - name: npm version 
      run: npm --version
    - name: Install dependencies 
      run: npm ci
    - name: Run build script inside package.json
      run: npm run build --if-present        
    - name: Test  
      run: npm tests
   
      
  on-failure:
    runs-on: ubuntu-latest
    needs: test
    if:  always()
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ needs.test.result }}
        SLACK_CHANNEL: general
        SLACK_USERNAME: 'Node-Bot'
        SLACK_TITLE: Workflow ${{ needs.test.result }}
        #SLACK_ICON: https://icons-for-free.com/iff/png/512/github+icon-1320168274457504277.png
        SLACK_MESSAGE_ON_SUCCESS: '🟢'
        SLACK_MESSAGE_ON_FAILURE: '🔴'
        SLACK_MESSAGE_ON_CANCEL: 'Cancel'
        SLACK_FOOTER: By Sharker3312
      
 
    

  to_dockerhub:
    runs-on: ubuntu-latest
    needs: test

    steps:
    
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: sharker3312/nodeapp
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    

      
